# Generated by Django 5.1.4 on 2024-12-15 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='description',
            new_name='summary',
        ),
    ]
